name: "Frogbot Security Scan"

on:
  pull_request_target:
    types: [opened, synchronize]  # Triggers scan-pr flow for every opened/updated pull request
  push:
    branches: 
      - master  # Updated branch to master

permissions:
  pull-requests: write
  contents: write
  security-events: write
  actions: read
  # [Mandatory If using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  # id-token: write 

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branch.
        branch: ["master"]  # Updated branch to master

    steps:
      - uses: jfrog/frogbot@v2
        env:
          JF_URL: 'https://hts2.jfrog.io'
          JF_USER: 'elumalaig@jfrog.com'
          JF_ACCESS_TOKEN: 'eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJ5ek11SE53Ukhfei0yTmJ1UWpwZVhXdFRqemJyWnVGcUtJRldvZXdYQW1VIn0.eyJpc3MiOiJqZmZlQDAxZThoa3NueTVndmthMTRhYThna2owYzdhIiwic3ViIjoiamZhY0AwMWU4aGtzbnk1Z3ZrYTE0YWE4Z2tqMGM3YS91c2Vycy9lbHVtYWxhaWdAamZyb2cuY29tIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9ucy9hZG1pbiIsImF1ZCI6IipAKiIsImlhdCI6MTc0NjQ3NzEwNCwianRpIjoiZWEwZTg1YzAtZWE2YS00Y2Y4LWI3ZGEtODg3MmNiY2QwZGRlIn0.Mz-eg64atCyCfOwd43DxURTyoYa7jBu-Inh_XAFST3hHVGWhz5gQvJ1-IFM0W4L8ZekGBVAYwrG4aSKW8ol9EFIY-DepsvcfyGvMsssTJ0AYDZ2L32zBNXskLaiKLKiOyB6wo_9jthW-0nSUK_MhVK3hhZUib0AxWWfOZlliPcX6j6426UK7le1PzaJgYvPRWp51gMfBB8NF-bssTZybhUO5A2vDuGX3E65J2aRJDFn_Fo0ZuHq5gz75-s7UXnT60b969t64It-hOyeqJyo5xi8sSq0VULH5x6X9HoEZ25zINJuMbjCGPfmuPQElBUDwsFqWL-QamlBq9cWJ4yiiJg'
          JF_GIT_BASE_BRANCH: 'master'
          JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}

